- name: Add nginxexporter group
  become: true
  group:
    name: nginxexporter
    state: present

- name: Add nginxexporter user
  become: true
  user:
    name: nginxexporter
    group: nginxexporter
    shell: /sbin/nologin
    create_home: false

- name: Copy nginx-exporter service
  become: true
  template:
    src: nginx-exporter.service
    dest: /lib/systemd/system/nginx-exporter.service
  register: nginx_exporter_service

- name: Start nginx-exporter
  become: true
  systemd:
    name: nginx-exporter
    enabled: true
    state: started

- name: Restart nginx-exporter
  become: true
  systemd:
    service: nginx-exporter
    daemon_reload: true
    state: restarted
  when: nginx_exporter_service.changed

# nginx

- name: Remove default config
  become: true
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default

- name: Create web root
  become: true
  file:
    path: /var/www/html/dns/
    state: directory

- name: Copy site index
  become: true
  template:
    src: index.html
    dest: /var/www/html/dns/index.html

- name: Copy server config
  become: true
  template:
    src: dns.emeraldonion.org
    dest: /etc/nginx/sites-available/dns.emeraldonion.org
  register: nginx_config

- name: Copy main server config
  become: true
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  register: nginx_config

- name: Symlink server config
  become: true
  file:
    src: /etc/nginx/sites-available/dns.emeraldonion.org
    dest: /etc/nginx/sites-enabled/dns.emeraldonion.org
    state: link

- name: Start nginx
  become: true
  systemd:
    name: nginx
    state: started
    enabled: true

- name: Reload nginx
  become: true
  systemd:
    name: nginx
    state: reloaded
  when: nginx_config.changed
