all:
  vars:
    domain: dns.emeraldonion.org
    ips:
      - 103.232.207.2
      - 2620:18c:2::2
      - 103.232.207.3
      - 2620:18c:2::3
  hosts:
    sea01:
      ansible_host: eodns-sea01
      cache_size: 8
      threads: 16
      bcg:
        asn: 65530
        peers:
          Transit:
            asn: 396507
            type: import-valid
            neighbors:
              - 23.129.64.121
              - 2620:18c:0:120::1

    sea02:
      ansible_host: eodns-sea02
      cache_size: 8
      threads: 16
      outgoing:
        ipv4: 23.129.64.123
        ipv6: 2620:18c:0:120::12
      bcg:
        asn: 65530
        peers:
          Transit:
            disabled: true
            asn: 396507
            type: import-valid
            neighbors:
              - 23.129.64.121
              - 2620:18c:0:120::1
