all:
  vars:
    domain: dns.emeraldonion.org
    ips:
      - 103.232.207.2
      - 2620:18c:2::2
      - 103.232.207.3
      - 2620:18c:2::3
  hosts:
    sea01:
      ansible_host: eodns-sea01
      cache_size: 8
      outgoing:
        ipv4: 23.129.64.122
        ipv6: 2620:18c:0:120::122

    sea02:
      ansible_host: eodns-sea02
      cache_size: 8
      outgoing:
        ipv4: 23.129.64.123
        ipv6: 2620:18c:0:120::123
