all:
  vars:
    tls_cert: /etc/letsencrypt/live/dns.emeraldonion.org/fullchain.pem
    tls_key: /etc/letsencrypt/live/dns.emeraldonion.org/privkey.pem
  hosts:
    sea01:
      ansible_host: eodns-sea01
      bcg:
        asn: 65530
        prefixes:
          - 103.232.207.2/32
          - 2620:18c:2::2/128
          - 103.232.207.3/32
          - 2620:18c:2::3/128
        peers:
          Transit:
            asn: 396507
            type: import-valid
            neighbors:
              - 23.129.64.121
              - 2620:18c:0:120::1

    sea02:
      ansible_host: eodns-sea02
      bcg:
        asn: 65530
        prefixes:
          - 103.232.207.2/32
          - 2620:18c:2::2/128
          - 103.232.207.3/32
          - 2620:18c:2::3/128
        peers:
          Transit:
            asn: 396507
            type: import-valid
            neighbors:
              - 23.129.64.121
              - 2620:18c:0:120::1
