- name: Add natesales apt repo for q DNS client and doqd DNS over QUIC deamon
  become: true
  apt_repository:
    repo: deb [trusted=yes] https://apt.fury.io/natesales/ /
    state: present

- name: Install knot-resolver repo
  become: true
  apt:
    deb: https://secure.nic.cz/files/knot-resolver/knot-resolver-release.deb

- name: Install packages
  become: true
  apt:
    update_cache: true
    pkg:
      - q # DNS client for Do{T,Q,H}
      - knot-dnsutils # kdig DNS client
      - knot-resolver=5.3.2-cznic.1 # knot resolver
      - knot-resolver-module-http=5.3.2-cznic.1 # knot resolver plugin for HTTP(s)
      - doqd # DNS over QUIC daemon
      - lua-luaossl-dev # SSL/TLS for knot-resolver priming query
      - lua-http # HTTP for knot-resolver priming query
