- name: Add natesales apt repo for q DNS client
  become: true
  apt_repository:
    repo: deb [trusted=yes] https://repo.natesales.net/apt /
    state: present

- name: Install knot-resolver repo
  become: true
  apt:
    deb: https://secure.nic.cz/files/knot-resolver/knot-resolver-release.deb

- name: Install packages
  become: true
  apt:
    update_cache: true
    pkg:
      - q # DNS client for Do{T,Q,H}
      - knot-resolver=5.3.1-cznic.1
      - knot-resolver-module-http=5.3.1-cznic.1
      - doqd # DNS over QUIC daemon
      - lua-luaossl-dev # SSL/TLS for knot-resolver priming query
      - lua-http # HTTP for knot-resolver priming query
