- name: Include package versions
  include_vars:
    file: packages.yml
    name: packages

- name: Add natesales apt repo for q DNS client and doqd DNS over QUIC deamon
  become: true
  apt_repository:
    repo: deb [trusted=yes] https://apt.fury.io/natesales/ /
    state: present

- name: Install knot-resolver repo
  become: true
  apt:
    deb: https://secure.nic.cz/files/knot-resolver/knot-resolver-release.deb

- name: Install odohd
  become: true
  apt:
    deb: "https://github.com/emeraldonion/odohd/releases/download/v{{ packages.additional.odohd }}/odohd_{{ packages.additional.odohd }}_linux_amd64.deb"

- name: Check if nginx_exporter exists
    stat:
      path: /usr/local/bin/nginx_exporter
    register: nginx_exporter

- name: Install nginx_exporter
  become: true
  unarchive:
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v{{ packages.additional.nginx_exporter }}/nginx-prometheus-exporter_{{ packages.additional.nginx_exporter }}_linux_amd64.tar.gz
    dest: /tmp/
    remote_src: true
  when: not nginx_exporter.stat.exists

- name: Move nginx_exporter
  become: true
  shell: mv /tmp/nginx-prometheus-exporter /usr/local/bin/nginx_exporter
  when: not nginx_exporter.stat.exists

- name: Check if node_exporter exists
  stat:
    path: /usr/local/bin/node_exporter
  register: node_exporter

- name: Install node_exporter
  become: true
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ packages.additional.node_exporter }}/node_exporter-{{ packages.additional.node_exporter }}.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: true
  when: not node_exporter.stat.exists

- name: Move node_exporter
  become: true
  shell: mv /tmp/node_exporter-{{ packages.additional.node_exporter }}.linux-amd64/node_exporter /usr/local/bin/node_exporter
  when: not node_exporter.stat.exists

- name: Mark node_exporter as executable
  become: true
  file:
    dest: /usr/local/bin/node_exporter
    mode: +x

- name: Install packages
  become: true
  apt:
    update_cache: true
    pkg: "{{ packages.apt }}"
