- name: Add natesales apt repo for bcg
  become: true
  apt_repository:
    repo: deb [trusted=yes] https://repo.natesales.net/apt /
    state: present

- name: Install bgpq4
  become: true
  apt:
    deb: http://mirrors.kernel.org/ubuntu/pool/universe/b/bgpq4/bgpq4_0.0.6-2_amd64.deb

- name: Install bcg and dependencies
  become: true
  apt:
    pkg:
      - bird2
      - bcg

- name: Create bcg directory
  become: true
  file:
    path: /etc/bcg/
    state: directory

- name: Copy bcg config
  become: true
  copy:
    content: "{{ bcg }}"
    dest: /etc/bcg/config.json
  register: bcg

- name: Start bird
  become: true
  systemd:
    name: bird
    state: started
    enabled: true

- name: Reload bcg config
  become: true
  shell: bcg -c /etc/bcg/config.json
  when: bcg.changed

- name: Add bcg crontab entry
  become: true
  cron:
    name: "bcg update"
    hour: "*/12"
    minute: "0"
    job: "/usr/local/bin/bcg -c /etc/bcg/config.json"
