- name: Add odohd group
  become: true
  group:
    name: odohd
    state: present

- name: Add odohd user
  become: true
  user:
    name: odohd
    group: odohd
    shell: /sbin/nologin
    create_home: false

- name: Copy odohd default
  become: true
  template:
    src: odohd
    dest: /etc/default/odohd
  register: odohd_default

- name: Copy odohd service
  become: true
  template:
    src: odohd.service
    dest: /lib/systemd/system/odohd.service
  register: odohd_service

- name: Start odohd
  become: true
  systemd:
    name: odohd
    enabled: true
    state: started

- name: Restart service
  become: true
  systemd:
    service: odohd
    daemon_reload: true
    state: restarted
  when: odohd_service.changed or odohd_default.changed
