- name: Create dummy interface file
  become: true
  copy:
    content: |
      #!/bin/bash
      ip link del dev any0
      ip link add dev any0 type dummy
      {% for ip in ips %}
      ip addr add dev any0 {{ ip }}
      {% endfor %}
      ip link set dev any0 up
    dest: /etc/networkd-dispatcher/routable.d/50-ifup-hooks
  register: iface_config

- name: Apply dummy interface config
  become: true
  shell: bash /etc/networkd-dispatcher/routable.d/50-ifup-hooks
  when: iface_config.changed

- name: Create bcg directory
  become: true
  file:
    path: /etc/bcg/
    state: directory

- name: Copy bcg config
  become: true
  copy:
    content: "{{ dict(bcg, prefixes=ips | map('ipsubnet') | list) }}"
    dest: /etc/bcg/config.json
  register: bcg

- name: Start bird
  become: true
  systemd:
    name: bird
    state: started
    enabled: true

- name: Reload bcg config
  become: true
  shell: bcg -c /etc/bcg/config.json
  when: bcg.changed

- name: Add bcg crontab entry
  become: true
  cron:
    name: "bcg update"
    hour: "*/12"
    minute: "0"
    job: "/usr/local/bin/bcg -c /etc/bcg/config.json"
