- name: Install dependencies
  pkgng:
    name: nginx,unbound
    state: present

- name: Remove default unbound config
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/unbound/unbound.conf.d/

- name: Remove default nginx config
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/
    - /etc/nginx/sites-available/
    - /etc/nginx/conf.d/

- name: Download dnsproxy
  get_url:
    url: "https://github.com/AdguardTeam/dnsproxy/releases/download/{{ vendor['dnsproxy-version'] }}/dnsproxy-freebsd-amd64-{{ vendor['dnsproxy-version'] }}.tar.gz"
    dest: /tmp/dnsproxy.tgz

- name: Extract dnsproxy
  unarchive:
    src: /tmp/dnsproxy.tgz
    dest: /tmp/

- name: Move dnsproxy to path
  copy:
    remote_src: true
    src: /tmp/dnsproxy
    dest: /usr/bin/dnsproxy
